server:
  port: 8080
  servlet:
    context-path: /o2o

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/o2o?useUnicode=true&characterEncoding=UTF8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    database: 0
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        min-idle: 0 # 连接池中的最小空闲连接 默认 0

mybatis:
  mapper-locations: classpath:mapping/*.xml # 指定xml的路径
  type-aliases-package: com.example.springboot_o2o.entity  # 指定POJO包来让mybatis自动扫描到自定义POJO
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名转换:Table{create_time} -> Entity{createTime}
    use-column-label: true # 使用列标签替换列别名 默认:true
    use-generated-keys: true # 使用jdbc的getGeneratedKeys获取数据库自增主键值
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台打印sql语句

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

